### ISSUE TITLE
how to use with prometheus operator

### ISSUE THREAD

**Issue by runningman84** [galexrt/container-node_exporter-textfiles#11]
It would be great to get some hint how to use this exporter with the prometheus operator helm chart...

**Comment by runningman84** [comment]
it lokks like this setup is needed:
```
    prometheus-node-exporter:
      extraArgs:
        - --collector.textfile.directory=/host/root/var/lib/node_exporter
```

**Comment by galexrt** [comment]
I'll look into adding more docs when working on a Helm chart for this image.

**Comment by galexrt** [comment]
I have added a node_exporter Configuration here https://github.com/galexrt/container-node_exporter-textfiles/blob/main/docs/node_exporter.md

For Kubernetes users a helm chart has been added, see https://github.com/galexrt/container-node_exporter-textfiles/tree/main/charts/node-exporter-textfiles

I hope this make using this project easier.

Please note that I have renamed the git repo and image name, see the notice in the readme: https://github.com/galexrt/container-node_exporter-textfiles#container-node_exporter-textfiles
