### ISSUE TITLE
Container Image Missing Python

### ISSUE THREAD

**Issue by jamey** [galexrt/container-node_exporter-textfiles#13]
After pulling the repo and installing via...

**microk8s helm3 install -f ./values.yaml node-exporter-textfiles .**

The resultant image does not work.  Containers init, but that's it.  Logs show the following.

Starting smartmon.sh loop ...
/usr/bin/env: 'python3': No such file or directory

I've traced this to an issue with the Docker image build - pulling python3 isn't working.

root@nuc0:~/node-exporter-textfiles/charts/node-exporter-textfiles# **microk8s kubectl exec --stdin --tty node-exporter-textfiles-5hc5q -- /bin/bash**
root@node-exporter-textfiles-5hc5q:/# **which python3**
root@node-exporter-textfiles-5hc5q:/# **apt-get install python3**
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3
root@node-exporter-textfiles-5hc5q:/# **apt -qq update**
36 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@node-exporter-textfiles-5hc5q:/# **apt-get install python3**
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  bzip2 file libmagic-mgc libmagic1 libmpdec2 libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib libreadline7 libsqlite3-0 mime-support python3-minimal python3.7
  python3.7-minimal readline-common xz-utils
Suggested packages:
  bzip2-doc python3-doc python3-tk python3-venv python3.7-venv python3.7-doc binutils binfmt-support readline-doc
The following NEW packages will be installed:
  bzip2 file libmagic-mgc libmagic1 libmpdec2 libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib libreadline7 libsqlite3-0 mime-support python3 python3-minimal python3.7
  python3.7-minimal readline-common xz-utils
0 upgraded, 17 newly installed, 0 to remove and 36 not upgraded.
Need to get 6153 kB of archives.
After this operation, 31.6 MB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by galexrt** [comment]
Please try setting `image.tag` to, e.g., `main` (for testing), or a more specific tag from here https://quay.io/repository/galexrt/node-exporter-textfiles?tab=tags in the `values.yaml`.

The `latest` container image is currently the defaulting to `latest` (which isn't updated anymore). I will update the default values.yaml with a better default value `main` and adding comments with the container image tag page to it.

**Comment by jamey** [comment]
Can confirm that sorts it!
