### ISSUE TITLE
Helm chart packaging

### ISSUE THREAD

**Issue by djjudas21** [galexrt/container-node_exporter-textfiles#15]
Hello,

Please would you consider creating a Helm chart repo with Github pages? Then it will be possible to easily install the Helm chart and follow updates.

https://helm.sh/docs/howto/chart_releaser_action/

I can help you, but it's quite straightforward :slightly_smiling_face:

**Comment by galexrt** [comment]
@djjudas21 Thanks! I totally forgot I still didn't added Helm chart publishing for this project.

Helm chart repo: https://galexrt.github.io/container-node_exporter-textfiles

See https://github.com/galexrt/container-node_exporter-textfiles/tree/main/charts/node-exporter-textfiles

**Comment by djjudas21** [comment]
Awesome, thanks!
