### ISSUE TITLE
no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by djjudas21** [galexrt/container-node_exporter-textfiles#16]
Installing from Helm on Kubernetes v1.22 gives error:

```
Release "node-exporter-textfiles" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "node-exporter-textfiles" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1"
ensure CRDs are installed first
```

These are the api-resources I have:

```
$ kubectl api-resources | grep -i PodSecurityPolicy
podsecuritypolicies               psp                 policy/v1beta1                         false        PodSecurityPolicy
```

So I think you need to change `extensions/v1beta1` to `policy/v1beta1` [here](https://github.com/galexrt/container-node_exporter-textfiles/blob/main/charts/node-exporter-textfiles/templates/podsecuritypolicy.yaml#L2)

**Comment by galexrt** [comment]
@djjudas21 As PodSecurityPolicies are going away in K8S 1.25 I have disabled them by default, but also as you suggested updated the API to `policy/v1beta1` in the latest Helm chart version `0.1.2`
