### ISSUE TITLE
Unable to deploy image since end of October

### ISSUE THREAD

**Issue by Cellane** [galexrt/container-node_exporter-textfiles#3]
On my personal server, I’m unable to deploy any version of this image newer than `v20201022-124227-096`.
Any attempt to deploy newer versions than that (tested just now with `v20201102-203151-584`, for some reason I can’t pull Docker images from Oct 25 and Oct 29 right now) end up with the container failing to start with the error message `Script smartmon.sh doesn't exist. Exiting 1`.

I have not changed any configuration on the server related to how the image is deployed, so I wonder if something changed in the image itself? Is there any configuration change necessary on my side that I somehow missed?

Thank you!

**Comment by galexrt** [comment]
The latest tag `v20201119-123603-585` seems to work fine for me. Any wy you can pull `v20201119-123603-585` and use that one?

The image has been kept backwards compatible, but there might have been some issues "a few tags ago" due to Docker build issues not having caused a failure.

**Comment by Cellane** [comment]
Wow, thank you for a super-fast response!
I have tried pulling and deploying tag `v20201119-123603-585` from both Docker Hub and Quay.io and unfortunately, I’m still unable to deploy the image. For the record, I’m using Dokku to manage my deployments, with no environmental variables configured, and following Docker options passed to Docker: `--privileged --restart=on-failure:10 -v /var/lib/dokku/data/storage/node-exporter:/var/lib/node_exporter`.

But even if I take Dokku out of the equation and remove all arguments and parameters, I can see the difference in outputs:

```bash
$ docker container run quay.io/galexrt/node-exporter-smartmon:v20201119-123603-585
Script smartmon.sh doesn't exist. Exiting 1
$ docker container run galexrt/node-exporter-smartmon:v20201022-124227-096
Starting smartmon.sh loop ...
```

When I override the `--entrypoint` and enter both versions with `/bin/sh` as an entrypoint, I can see one difference:

- In the `v20201022-124227-096` version, `smartmon.sh` is located in the root directory `/`;
- In the newer versions, incl. `v20201119-123603-585`, `smartmon.sh` is located in the `/scripts` directory.

Though I’m not sure if that should play any role, as I can see that `entrypoint.sh` was also adjusted accordingly…

**Comment by Cellane** [comment]
Wait a second… Isn’t the condition in the `entrypoint.sh` exactly reversed?

Shouldn’t the line `14` look like this? `if [ ! -f "/scripts/${SCRIPT}" ]; then`? `-f` tests for existence of a file, not absence, right?

**Comment by galexrt** [comment]
Yep, you are right I have pushed a commit and the tag `v20201124-011639-855`.
The image tag should be available on Docker Hub and Quay.io in hopefully around 15-30 minutes.

Thanks for finding that!

Edit: Docker Hub and Quay.io should be completed now and the image should be available under tag `v20201124-011639-855` as mentioned.

**Comment by Cellane** [comment]
Thank you for fixing this quickly! Will test the new version once server picks up the updated tag.
