### ISSUE TITLE
Integrate with Prometheus AlertManager

### ISSUE THREAD

**Issue by Akruidenberg** [galexrt/container-node_exporter-textfiles#5]
I would like to integrate this container with Prometheus AlertManager to receive notifications when a hard drive is unhealthy.

What are the steps beside the basic configs to get this working?

@Galexrt do you have any example for this to get this running. Maybe you have this running by yourself. 

If you need any more info, please let me know!

Thanks in advance.

**Comment by galexrt** [comment]
You need to look at the following points:

* You need to have node_exporter configured to pick up the textfile exported metrics by this container image. node_exporter's `textfile` is enabled by default though you probably need to adjust the textfile directory to be the same as this container image is writing the metrics to.
* Alerts configured in Prometheus that check disk health based on the metrics.
* Have some dashboards in Grafana to visualize the metrics if you wnat to have that, there is an example dashboard in this repo at https://github.com/galexrt/container-node_exporter-smartmon/tree/main/grafana.

**Comment by Akruidenberg** [comment]
Did some research in the Prometheus and see that **smartmon_device_smart_healthy=** is used for this. 
I have some trouble with Prometheus/alartmanager to set-up rules.
Looks like i must set a rule when **smartmon_device_smart_healthy > 0** send a message. 
Prometheus/alaertmanager is new for me, so its difficult to set the rules file. 

I would to like to send it with a webhook to a Gotify server.

**Comment by galexrt** [comment]
Checkout the docs of Prometheus, Alertmanager and the textfile metrics scripts:

* Prometheus Docs regarding Alerting Rules: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
* Alertmanager Docs Configuration: https://prometheus.io/docs/alerting/latest/configuration/#configuration
* Alertmanager Docs for webhook receiver: https://prometheus.io/docs/alerting/latest/configuration/#webhook_config
* Textfile metrics scripts Repo: https://github.com/prometheus-community/node-exporter-textfile-collector-scripts
* node_exporter Textilfe Collection: https://github.com/prometheus/node_exporter#textfile-collector

There's probably some guides to Prometheus and Alerting in general available on the internet.

***

I'm going to close this issue as there isn't really much that can be provided besides links to docs to Prometheus, Alertmanager and the other components needed.
